import ActionPlanCard from "./ActionPlanCard";

export default function ActionPlan({ data }) {
  if (!data || data.length === 0) {
    return null;
  }

  return (
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-8">
      <div>
        <h2 className="text-2xl font-semibold text-white">
          AI Action Plan
        </h2>

        <p className="mt-2 text-sm text-slate-400">
          Prioritized engineering recommendations generated by DevLens AI to
          improve repository quality and long-term maintainability.
        </p>
      </div>

      <div className="mt-8 space-y-6">
        {data.map((plan) => (
          <ActionPlanCard
            key={plan.title}
            phase={plan.phase}
            priority={plan.priority}
            estimatedTime={plan.estimatedTime}
            title={plan.title}
            description={plan.description}
            reason={plan.reason}
          />
        ))}
      </div>
    </section>
  );
}