import ActionPlanCard from "./ActionPlanCard";

const actionPlans = [
  {
    phase: "Immediate",
    priority: "High",
    estimatedTime: "15 min",
    title: "Add Readiness Probes",
    description:
      "Configure readiness probes for Kubernetes deployments to improve rollout reliability and reduce production downtime.",
    reason:
      "This helps prevent traffic from reaching unhealthy containers and enables safer deployments.",
  },
  {
    phase: "Next",
    priority: "Medium",
    estimatedTime: "45 min",
    title: "Increase Test Coverage",
    description:
      "Expand automated unit and integration testing for critical services and API endpoints.",
    reason:
      "Improved test coverage reduces regressions and increases confidence during future releases.",
  },
  {
    phase: "Future",
    priority: "Low",
    estimatedTime: "2 hrs",
    title: "Implement Centralized Observability",
    description:
      "Introduce centralized logging, metrics, and monitoring for better production visibility.",
    reason:
      "Observability enables faster debugging, proactive monitoring, and long-term system reliability.",
  },
];

export default function ActionPlan() {
  return (
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-8">
      <div>
        <h2 className="text-2xl font-semibold text-white">
          AI Action Plan
        </h2>

        <p className="mt-2 text-sm text-slate-400">
          Prioritized engineering recommendations generated by
          DevLens AI to improve repository quality and
          long-term maintainability.
        </p>
      </div>

      <div className="mt-8 space-y-6">
        {actionPlans.map((plan) => (
          <ActionPlanCard
            key={plan.title}
            {...plan}
          />
        ))}
      </div>
    </section>
  );
}