import { ListChecks } from "lucide-react";
import ActionPlanCard from "./ActionPlanCard";

export default function ActionPlan({ data }) {
  const actionItems = data || [];

  return (
    <section className="rounded-2xl border border-slate-800 bg-slate-950/60 p-6">
      <div className="mb-6 flex items-center gap-3">
        <div className="rounded-xl bg-blue-500/10 p-2">
          <ListChecks className="h-6 w-6 text-blue-400" />
        </div>

        <div>
          <h2 className="text-2xl font-bold text-white">Action Items</h2>
          <p className="mt-1 text-sm text-slate-400">
            Prioritized engineering work generated by DevLens AI.
          </p>
        </div>
      </div>

      {actionItems.length === 0 ? (
        <div className="rounded-xl border border-dashed border-slate-700 bg-slate-900/40 py-14 text-center">
          <ListChecks className="mx-auto h-12 w-12 text-slate-500" />
          <h3 className="mt-5 text-xl font-semibold text-white">
            No Action Items
          </h3>
          <p className="mx-auto mt-2 max-w-md text-sm text-slate-400">
            The AI review did not return prioritized action items for this run.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {actionItems.map((plan, index) => (
            <ActionPlanCard
              key={plan.title || index}
              phase={plan.phase}
              priority={plan.priority}
              estimatedTime={plan.estimatedTime}
              title={plan.title}
              description={plan.description}
              reason={plan.reason}
            />
          ))}
        </div>
      )}
    </section>
  );
}
