import {
  Sparkles,
  Brain,
  TrendingUp,
} from "lucide-react";

export default function AIExecutiveSummary() {
  return (
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-8">
      {/* Header */}
      <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex items-start gap-4">
          <div className="rounded-xl bg-violet-500/10 p-4">
            <Sparkles className="h-7 w-7 text-violet-400" />
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">
              AI Executive Summary
            </h2>

            <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">
              A high-level engineering assessment generated by
              DevLens AI after analyzing the repository's
              architecture, deployment, technical debt,
              engineering health, and pull requests.
            </p>
          </div>
        </div>

        <div className="inline-flex items-center gap-2 rounded-xl border border-violet-500/20 bg-violet-500/10 px-4 py-2">
          <Brain className="h-5 w-5 text-violet-400" />

          <span className="text-sm font-medium text-violet-300">
            AI Generated
          </span>
        </div>
      </div>

      {/* Summary Card */}
      <div className="mt-8 rounded-xl border border-slate-800 bg-slate-950/60 p-8">
        <div className="flex items-start gap-4">
          <div className="rounded-lg bg-blue-500/10 p-3">
            <TrendingUp className="h-6 w-6 text-blue-400" />
          </div>

          <div className="flex-1">
            <h3 className="text-lg font-semibold text-white">
              Repository Assessment
            </h3>

            <p className="mt-5 leading-8 text-slate-300">
              This repository demonstrates a well-structured
              engineering foundation with clear project
              organization and deployment practices. The
              overall engineering health is strong, while a few
              opportunities remain around automated testing,
              deployment validation, observability, and long-
              term maintainability. Addressing these areas will
              improve reliability, scalability, and developer
              productivity.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}