import {
  Box,
  Container,
  Cpu,
  Database,
  Layers,
  Lightbulb,
  Server,
} from "lucide-react";
import ArchitectureCard from "./ArchitectureCard";
import TechnologyCard from "./TechnologyCard";

const technologyIcons = {
  React: Layers,
  "Node.js": Server,
  Node: Server,
  Express: Server,
  MongoDB: Database,
  PostgreSQL: Database,
  MySQL: Database,
  Redis: Cpu,
  Docker: Container,
  Kubernetes: Box,
};

export default function AIReviewRecommendations({
  architectureSuggestions = [],
  technologyInsights = [],
}) {
  return (
    <section className="rounded-2xl border border-slate-800 bg-slate-950/60 p-6">
      <div className="mb-6 flex items-center gap-3">
        <div className="rounded-xl bg-yellow-500/10 p-2">
          <Lightbulb className="h-6 w-6 text-yellow-400" />
        </div>

        <div>
          <h2 className="text-2xl font-bold text-white">
            Engineering Recommendations
          </h2>
          <p className="mt-1 text-sm text-slate-400">
            Strategic architecture and technology improvements generated by AI.
          </p>
        </div>
      </div>

      {architectureSuggestions.length === 0 &&
      technologyInsights.length === 0 ? (
        <div className="rounded-xl border border-dashed border-slate-700 bg-slate-900/40 py-14 text-center">
          <Lightbulb className="mx-auto h-12 w-12 text-slate-500" />
          <h3 className="mt-5 text-xl font-semibold text-white">
            No Recommendations
          </h3>
          <p className="mx-auto mt-2 max-w-md text-sm text-slate-400">
            The AI review did not return engineering recommendations for this
            run.
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {architectureSuggestions.length > 0 && (
            <div className="grid gap-4 xl:grid-cols-2">
              {architectureSuggestions.map((suggestion, index) => (
                <ArchitectureCard
                  key={suggestion.title || index}
                  title={suggestion.title}
                  priority={suggestion.priority}
                  recommendation={suggestion.recommendation}
                  benefits={suggestion.benefits}
                />
              ))}
            </div>
          )}

          {technologyInsights.length > 0 && (
            <div>
              <div className="mb-4 border-t border-slate-800 pt-6">
                <h3 className="text-lg font-semibold text-white">
                  Technology Recommendations
                </h3>
                <p className="mt-1 text-sm text-slate-400">
                  Technology-specific observations and optimization
                  opportunities.
                </p>
              </div>

              <div className="grid gap-4 md:grid-cols-2">
                {technologyInsights.map((technology, index) => (
                  <TechnologyCard
                    key={technology.name || index}
                    icon={technologyIcons[technology.name] || Layers}
                    name={technology.name}
                    category={technology.category}
                    insight={technology.insight}
                  />
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </section>
  );
}
