import ArchitectureCard from "./ArchitectureCard";

export default function ArchitectureSuggestions({ data }) {
  if (!data || data.length === 0) {
    return null;
  }

  return (
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-8">
      <div>
        <h2 className="text-2xl font-semibold text-white">
          Architecture Suggestions
        </h2>

        <p className="mt-2 text-sm text-slate-400">
          Strategic architectural recommendations generated by DevLens AI to
          improve scalability, maintainability, and long-term engineering
          quality.
        </p>
      </div>

      <div className="mt-8 grid gap-6 xl:grid-cols-2">
        {data.map((suggestion) => (
          <ArchitectureCard
            key={suggestion.title}
            title={suggestion.title}
            priority={suggestion.priority}
            recommendation={suggestion.recommendation}
            benefits={suggestion.benefits}
          />
        ))}
      </div>
    </section>
  );
}