import ArchitectureCard from "./ArchitectureCard";

const suggestions = [
  {
    title: "Feature-Based Architecture",
    priority: "Medium",
    recommendation:
      "Group related components, services, hooks, and utilities into feature modules to improve maintainability and scalability as the project grows.",
    benefits: [
      "Improves code organization",
      "Reduces coupling between features",
      "Simplifies onboarding for new developers",
    ],
  },
  {
    title: "Centralized Configuration",
    priority: "High",
    recommendation:
      "Consolidate environment variables and application configuration into a dedicated configuration layer with validation.",
    benefits: [
      "Easier environment management",
      "Safer deployments",
      "Better configuration consistency",
    ],
  },
  {
    title: "Repository Pattern",
    priority: "Medium",
    recommendation:
      "Introduce a repository layer to separate data access from business logic, improving maintainability and testability.",
    benefits: [
      "Cleaner service layer",
      "Simpler unit testing",
      "Reduced database coupling",
    ],
  },
];

export default function ArchitectureSuggestions() {
  return (
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-8">
      <div>
        <h2 className="text-2xl font-semibold text-white">
          Architecture Suggestions
        </h2>

        <p className="mt-2 text-sm text-slate-400">
          Strategic architectural recommendations generated by
          DevLens AI to improve scalability, maintainability,
          and long-term engineering quality.
        </p>
      </div>

      <div className="mt-8 grid gap-6 xl:grid-cols-2">
        {suggestions.map((suggestion) => (
          <ArchitectureCard
            key={suggestion.title}
            {...suggestion}
          />
        ))}
      </div>
    </section>
  );
}