const {
    REPOSITORY_REVIEW_SYSTEM_PROMPT,
} = require("./prompts/repositoryReview.prompt");

const buildRepositorySection = (repository) => {
    const data = repository ?? {};

    return `
Repository Information

Name: ${data.name ?? "Unknown"}
Description: ${data.description ?? "Not Available"}
Primary Language: ${data.language ?? "Unknown"}
Stars: ${data.stars ?? 0}
Default Branch: ${data.defaultBranch ?? "Unknown"}
Visibility: ${data.private ? "Private" : "Public"}
`;
};

const buildEngineeringHealthSection = (engineeringHealth) => {
    const data = engineeringHealth ?? {};

    return `
Engineering Health

Overall Engineering Score: ${data.engineeringScore ?? "N/A"}
Engineering Status: ${data.status ?? "Unknown"}

Engineering Strengths:
${
    data.strengths?.length
        ? data.strengths.map((item) => `- ${item}`).join("\n")
        : "None"
}

Priority Recommendations:
${
    data.priorityRecommendations?.length
        ? data.priorityRecommendations.map((item) => `- ${item}`).join("\n")
        : "None"
}
`;
};

const buildRepositoryHealthSection = (repositoryHealth) => {
    const data = repositoryHealth ?? {};

    return `
Repository Health

Health Score: ${data.healthScore ?? "N/A"}
Activity Score: ${data.activityScore ?? "N/A"}
Documentation Score: ${data.documentationScore ?? "N/A"}
Maintenance Score: ${data.maintenanceScore ?? "N/A"}

Recommendations:
${
    data.recommendations?.length
        ? data.recommendations.map((item) => `- ${item}`).join("\n")
        : "None"
}
`;
};

const buildArchitectureSection = (architecture) => {
    const data = architecture ?? {};

    return `
Architecture Analysis

Complexity Score: ${data.complexityScore ?? "N/A"}
Node Count: ${data.nodeCount ?? "N/A"}
Edge Count: ${data.edgeCount ?? "N/A"}

Circular Dependencies:
${data.hasCircularDependency ? "Yes" : "No"}
`;
};

const buildTechnicalDebtSection = (technicalDebt) => {
    const data = technicalDebt ?? {};

    return `
Technical Debt

Technical Debt Score:
${data.technicalDebtScore ?? "N/A"}

Maintainability Score:
${data.maintainabilityScore ?? "N/A"}

Large File Count:
${data.largeFileCount ?? 0}

Dead File Count:
${data.deadFileCount ?? 0}

Circular Dependency Count:
${data.circularDependencyCount ?? 0}

Deep Dependency Chain Count:
${data.deepDependencyChainCount ?? 0}

Recommendations:
${
    data.recommendations?.length
        ? data.recommendations.map((item) => `- ${item}`).join("\n")
        : "None"
}
`;
};

const buildDeploymentSection = (deployment) => {
    const data = deployment ?? {};

    return `
Deployment Readiness

Deployment Score:
${data.deploymentScore ?? "N/A"}

Deployment Status:
${data.deploymentStatus ?? "Unknown"}

Infrastructure Score:
${data.infrastructureScore ?? "N/A"}

Configuration Score:
${data.configurationScore ?? "N/A"}

Build Readiness Score:
${data.buildReadinessScore ?? "N/A"}

CI/CD Score:
${data.ciCdScore ?? "N/A"}

Strengths:
${
    data.strengths?.length
        ? data.strengths.map((item) => `- ${item}`).join("\n")
        : "None"
}

Warnings:
${
    data.warnings?.length
        ? data.warnings.map((item) => `- ${item}`).join("\n")
        : "None"
}

Critical Issues:
${
    data.criticalIssues?.length
        ? data.criticalIssues.map((item) => `- ${item}`).join("\n")
        : "None"
}

Recommendations:
${
    data.recommendations?.length
        ? data.recommendations.map((item) => `- ${item}`).join("\n")
        : "None"
}
`;
};

const buildPullRequestSection = (pullRequestRisk) => {
    const data = pullRequestRisk ?? {};

    return `
Pull Request Risk

PR Number:
${data.prNumber ?? "N/A"}

Title:
${data.title ?? "N/A"}

Risk Score:
${data.riskScore ?? "N/A"}

Risk Level:
${data.riskLevel ?? "Unknown"}

Files Changed:
${data.totalFiles ?? 0}

Additions:
${data.additions ?? 0}

Deletions:
${data.deletions ?? 0}

Dependency Changes:
${data.hasDependencyChanges ? "Yes" : "No"}

Configuration Changes:
${data.hasConfigurationChanges ? "Yes" : "No"}

Recommendations:
${
    data.recommendations?.length
        ? data.recommendations.map((item) => `- ${item}`).join("\n")
        : "None"
}
`;
};

const buildRepositoryReviewPrompt = (analysis) => {
    const repositoryAnalysis = [
        buildRepositorySection(analysis.repository),
        buildEngineeringHealthSection(analysis.engineeringHealth),
        buildRepositoryHealthSection(analysis.repositoryHealth),
        buildArchitectureSection(analysis.architecture),
        buildTechnicalDebtSection(analysis.technicalDebt),
        buildDeploymentSection(analysis.deployment),
        buildPullRequestSection(analysis.pullRequestRisk),
    ].join("\n\n");

    return `
${REPOSITORY_REVIEW_SYSTEM_PROMPT}

Below is the engineering analysis generated by DevLens.

${repositoryAnalysis}

Using ONLY the repository analysis above:

1. Evaluate the repository objectively.
2. Do not invent information.
3. Follow the required JSON schema exactly.
4. Return valid JSON that can be parsed using JSON.parse().
5. Do not include markdown or explanations outside the JSON object.
`;
};

module.exports = {
    buildRepositorySection,
    buildEngineeringHealthSection,
    buildRepositoryHealthSection,
    buildArchitectureSection,
    buildTechnicalDebtSection,
    buildDeploymentSection,
    buildPullRequestSection,
    buildRepositoryReviewPrompt,
};