const {
    REPOSITORY_REVIEW_SYSTEM_PROMPT,
} = require("./prompts/repositoryReview.prompt");

const buildRepositorySection = (repository = {}) => `
Repository Information

Name: ${repository.name ?? "Unknown"}
Description: ${repository.description ?? "Not Available"}
Primary Language: ${repository.language ?? "Unknown"}
Stars: ${repository.stars ?? 0}
Forks: ${repository.forks ?? 0}
Default Branch: ${repository.defaultBranch ?? "Unknown"}
Visibility: ${repository.private ? "Private" : "Public"}
`;

const buildEngineeringHealthSection = (engineeringHealth = {}) => `
Engineering Health

Overall Engineering Score: ${engineeringHealth.engineeringScore ?? "N/A"}
Engineering Status: ${engineeringHealth.status ?? "Unknown"}

Engineering Strengths:
${
    engineeringHealth.strengths?.length
        ? engineeringHealth.strengths.map((item) => `- ${item}`).join("\n")
        : "None"
}

Priority Recommendations:
${
    engineeringHealth.priorityRecommendations?.length
        ? engineeringHealth.priorityRecommendations
              .map((item) => `- ${item}`)
              .join("\n")
        : "None"
}
`;

const buildRepositoryHealthSection = (repositoryHealth = {}) => `
Repository Health

Health Score: ${repositoryHealth.healthScore ?? "N/A"}
Activity Score: ${repositoryHealth.activityScore ?? "N/A"}
Documentation Score: ${repositoryHealth.documentationScore ?? "N/A"}
Maintenance Score: ${repositoryHealth.maintenanceScore ?? "N/A"}
`;

const buildArchitectureSection = (architecture = {}) => `
Architecture Analysis

Complexity Score: ${architecture.complexityScore ?? "N/A"}
Node Count: ${architecture.nodeCount ?? "N/A"}
Edge Count: ${architecture.edgeCount ?? "N/A"}

Circular Dependencies:
${architecture.hasCircularDependency ? "Yes" : "No"}

Circular Dependency Count:
${architecture.circularDependencies?.length ?? 0}
`;

const buildTechnicalDebtSection = (technicalDebt = {}) => `
Technical Debt

Technical Debt Score:
${technicalDebt.technicalDebtScore ?? "N/A"}

Maintainability Score:
${technicalDebt.maintainabilityScore ?? "N/A"}

Large Files:
${
    technicalDebt.largeFiles?.length
        ? technicalDebt.largeFiles
              .map(
                  (file) =>
                      `- ${file.file || file.path} (${file.lines ?? "Unknown"} LOC)`
              )
              .join("\n")
        : "None"
}

Dead Files:
${
    technicalDebt.deadFiles?.length
        ? technicalDebt.deadFiles
              .map((file) => `- ${file.file || file}`)
              .join("\n")
        : "None"
}

Deep Dependency Chains:
${
    technicalDebt.deepDependencyChains?.length
        ? technicalDebt.deepDependencyChains
              .map(
                  (chain) =>
                      `- Depth ${chain.depth ?? "Unknown"} (${chain.path ?? ""})`
              )
              .join("\n")
        : "None"
}
`;

const buildDeploymentSection = (deployment = {}) => `
Deployment Readiness

Deployment Score:
${deployment.deploymentScore ?? "N/A"}

Deployment Status:
${deployment.status ?? "Unknown"}

Dockerfile:
${deployment.infrastructure?.dockerfile ? "Present" : "Missing"}

Docker Compose:
${deployment.infrastructure?.dockerCompose ? "Present" : "Missing"}

GitHub Actions:
${deployment.ciCd?.githubActions ? "Configured" : "Not Configured"}
`;

const buildPullRequestSection = (pullRequestRisk = {}) => `
Pull Request Risk

Risk Score:
${pullRequestRisk.riskScore ?? "N/A"}

Risk Level:
${pullRequestRisk.riskLevel ?? "Unknown"}

Critical Files Changed:
${pullRequestRisk.criticalFiles ?? 0}

Dependency Changes:
${pullRequestRisk.dependencyChanges ? "Yes" : "No"}

Configuration Changes:
${pullRequestRisk.configurationChanges ? "Yes" : "No"}
`;

const buildRepositoryReviewPrompt = (analysis) => {
    const {
        repository,
        engineeringHealth,
        repositoryHealth,
        architecture,
        technicalDebt,
        deployment,
        pullRequestRisk,
    } = analysis;

    const repositoryAnalysis = [
        buildRepositorySection(repository),
        buildEngineeringHealthSection(engineeringHealth),
        buildRepositoryHealthSection(repositoryHealth),
        buildArchitectureSection(architecture),
        buildTechnicalDebtSection(technicalDebt),
        buildDeploymentSection(deployment),
        buildPullRequestSection(pullRequestRisk),
    ].join("\n\n");

    return `
${REPOSITORY_REVIEW_SYSTEM_PROMPT}

Below is the engineering analysis generated by DevLens.

${repositoryAnalysis}

Using ONLY the repository analysis above:

1. Evaluate the repository objectively.
2. Do not invent information.
3. Follow the required JSON schema exactly.
4. Return valid JSON that can be parsed using JSON.parse().
5. Do not include markdown or explanations outside the JSON object.
`;
};

module.exports = {
    buildRepositorySection,
    buildEngineeringHealthSection,
    buildRepositoryHealthSection,
    buildArchitectureSection,
    buildTechnicalDebtSection,
    buildDeploymentSection,
    buildPullRequestSection,
    buildRepositoryReviewPrompt,
};